# permissions for end users to view apachewebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apacheweb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apache-operator
    app.kubernetes.io/part-of: apache-operator
    app.kubernetes.io/managed-by: kustomize
  name: apacheweb-viewer-role
rules:
- apiGroups:
  - apacheweb.arsenal.dev
  resources:
  - apachewebs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apacheweb.arsenal.dev
  resources:
  - apachewebs/status
  verbs:
  - get
